-- 1. LIMPEZA
DROP TABLE IF EXISTS tb_avaliacoes_psicogeneticas CASCADE;
DROP TABLE IF EXISTS tb_alunos CASCADE;
DROP TABLE IF EXISTS tb_professor_turma CASCADE;
DROP TABLE IF EXISTS tb_turmas CASCADE;
DROP TABLE IF EXISTS tb_usuarios CASCADE;

-- 2. TABELAS

CREATE TABLE tb_usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL, 
    perfil VARCHAR(50) NOT NULL,
    escola VARCHAR(255),
    telefone VARCHAR(20),
    data_nascimento DATE,
    localidade VARCHAR(255),
    CONSTRAINT chk_usuario_perfil CHECK (perfil IN ('ADMINISTRADOR', 'PROFESSOR'))
);
CREATE INDEX idx_usuarios_email ON tb_usuarios(email);

CREATE TABLE tb_turmas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    ano_escolar VARCHAR(50) NOT NULL,
    turno VARCHAR(50) NOT NULL,
    CONSTRAINT chk_turma_ano CHECK (ano_escolar IN ('PRIMEIRO_ANO', 'SEGUNDO_ANO', 'TERCEIRO_ANO', 'QUARTO_ANO', 'QUINTO_ANO')),
    CONSTRAINT chk_turma_turno CHECK (turno IN ('MANHA', 'TARDE', 'INTEGRAL'))
);

CREATE TABLE tb_professor_turma (
    professor_id BIGINT NOT NULL REFERENCES tb_usuarios(id) ON DELETE CASCADE,
    turma_id BIGINT NOT NULL REFERENCES tb_turmas(id) ON DELETE CASCADE,
    PRIMARY KEY (professor_id, turma_id)
);
CREATE INDEX idx_prof_turma_reverso ON tb_professor_turma(turma_id, professor_id);

CREATE TABLE tb_alunos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    data_nascimento DATE NOT NULL,
    turma_id BIGINT NOT NULL REFERENCES tb_turmas(id) ON DELETE RESTRICT
);
CREATE INDEX idx_alunos_turma_id ON tb_alunos(turma_id);

CREATE TABLE tb_avaliacoes_psicogeneticas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id BIGINT NOT NULL REFERENCES tb_alunos(id) ON DELETE CASCADE,
    professor_id BIGINT NOT NULL REFERENCES tb_usuarios(id) ON DELETE RESTRICT,
    data_avaliacao DATE NOT NULL,
    bimestre VARCHAR(50) NOT NULL,
    nivel VARCHAR(50) NOT NULL,
    observacao TEXT,
    CONSTRAINT chk_avaliacao_bimestre CHECK (bimestre IN ('PRIMEIRO_BIMESTRE', 'SEGUNDO_BIMESTRE', 'TERCEIRO_BIMESTRE', 'QUARTO_BIMESTRE')),
    CONSTRAINT chk_avaliacao_nivel CHECK (nivel IN ('ICONICA', 'GARATUJA', 'PRE_SILABICO', 'SILABICO_COM_VALOR_SONORO', 'SILABICO_SEM_VALOR_SONORO', 'ALFABETICO', 'ORTOGRAFICO'))
);
CREATE INDEX idx_avaliacoes_aluno_id ON tb_avaliacoes_psicogeneticas(aluno_id);
CREATE INDEX idx_avaliacoes_dashboard ON tb_avaliacoes_psicogeneticas(nivel, bimestre);

CREATE UNIQUE INDEX uk_avaliacao_aluno_bimestre_ano 
ON tb_avaliacoes_psicogeneticas (aluno_id, bimestre, EXTRACT(YEAR FROM data_avaliacao));


INSERT INTO tb_usuarios (nome, email, senha, perfil) VALUES 
('Admin', 'admin@lunetras.com', '$2a$10$X.Iq3z8H0s8e8hGq1t8Qh.8N9z8e8hGq1t8Qh.8N9z8e8hGq1t8Qh', 'ADMINISTRADOR'),
('Prof Fernanda', 'fernanda@escola.com', '$2a$10$X.Iq3z8H0s8e8hGq1t8Qh.8N9z8e8hGq1t8Qh.8N9z8e8hGq1t8Qh', 'PROFESSOR');

INSERT INTO tb_turmas (nome, ano_escolar, turno) VALUES 
('Turma 1º Ano A', 'PRIMEIRO_ANO', 'MANHA');

-- Assumindo que o Admin pegou ID 1, a Prof pegou ID 2, e a Turma pegou ID 1
INSERT INTO tb_professor_turma (professor_id, turma_id) VALUES (2, 1);

INSERT INTO tb_alunos (nome, data_nascimento, turma_id) VALUES 
('Enzo Almeida', '2017-05-14', 1),
('Sophia Martins', '2017-08-22', 1)